### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by swieer** [anyRTC/AriOSSDK#1]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ARVideoEncoderConfiguration", referenced from:
      objc-class-ref in VideoChatViewController.o
  "_OBJC_CLASS_$_ARtcEngineKit", referenced from:
      objc-class-ref in VideoChatViewController.o
  "_OBJC_CLASS_$_ARtcVideoCanvas", referenced from:
      objc-class-ref in VideoChatViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Dync-BoYuan** [comment]
用真机运行，暂不支持模拟器
